# Generated by Django 6.0.1 on 2026-01-07 00:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(help_text='Titre/description courte de la demande', max_length=200)),
                ('merchandise_type', models.CharField(choices=[('GENERAL', 'Marchandise générale'), ('FRAGILE', 'Fragile'), ('PERISHABLE', 'Périssable'), ('DANGEROUS', 'Matières dangereuses'), ('ELECTRONIC', 'Électronique'), ('FURNITURE', 'Mobilier'), ('FOOD', 'Alimentaire'), ('OTHER', 'Autre')], default='GENERAL', max_length=20)),
                ('merchandise_description', models.TextField(help_text='Description détaillée de la marchandise')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Poids en kg', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('volume', models.DecimalField(decimal_places=2, help_text='Volume en m³', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('pickup_address', models.TextField(help_text='Adresse de collecte')),
                ('pickup_city', models.CharField(max_length=100)),
                ('pickup_coordinates', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_address', models.TextField(help_text='Adresse de livraison')),
                ('delivery_city', models.CharField(max_length=100)),
                ('delivery_coordinates', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_pickup_date', models.DateTimeField(help_text='Date souhaitée de collecte')),
                ('preferred_delivery_date', models.DateTimeField(blank=True, help_text='Date souhaitée de livraison', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('OFFERS_RECEIVED', 'Offres reçues'), ('ASSIGNED', 'Assignée'), ('IN_PROGRESS', 'En cours'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Basse'), ('NORMAL', 'Normale'), ('HIGH', 'Haute'), ('URGENT', 'Urgente')], default='NORMAL', max_length=10)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, help_text='Prix estimé par le client', max_digits=10, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_frequency', models.CharField(blank=True, choices=[('DAILY', 'Quotidien'), ('WEEKLY', 'Hebdomadaire'), ('MONTHLY', 'Mensuel'), ('SEASONAL', 'Saisonnier')], max_length=20, null=True)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_phone', models.CharField(max_length=15)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Demande de transport',
                'verbose_name_plural': 'Demandes de transport',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TypeDocumentLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('profil', models.CharField(choices=[('PME', 'PME'), ('AGRICULTEUR', 'AGRICULTEUR'), ('PARTICULIER', 'PARTICULIER'), ('TRANSPORTEUR', 'TRANSPORTEUR')], default=('PME', 'PME'), max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('firstname', models.CharField(blank=True, max_length=30, null=True)),
                ('lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format : '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Le mot de passe doit contenir au moins 8 caractères, une lettre, un chiffre et un caractère spécial.', regex='^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*#?&])[A-Za-z\\d@$!%*#?&]{8,}$')])),
                ('role', models.CharField(choices=[('DATA ADMIN', 'DATA ADMIN'), ('ADMIN', 'ADMIN'), ('MODERATOR', 'MODERATOR'), ('PME', 'PME'), ('AGRICULTEUR', 'AGRICULTEUR'), ('PARTICULIER', 'PARTICULIER'), ('TRANSPORTEUR', 'TRANSPORTEUR')], max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users_photo/')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('INVOICE', 'Facture'), ('CERTIFICATE', 'Certificat'), ('INSURANCE', 'Assurance'), ('PERMIT', 'Autorisation'), ('PHOTO', 'Photo'), ('OTHER', 'Autre')], max_length=20)),
                ('file', models.FileField(upload_to='transport_documents/%Y/%m/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('transport_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='africa_logistic.transportrequest')),
            ],
            options={
                'verbose_name': 'Document de demande',
                'verbose_name_plural': 'Documents de demandes',
            },
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='assigned_transporter',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TRANSPORTEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_transports', to='africa_logistic.user'),
        ),
        migrations.AddField(
            model_name='transportrequest',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role__in': ['PME', 'PARTICULIER', 'AGRICULTEUR']}, on_delete=django.db.models.deletion.CASCADE, related_name='transport_requests', to='africa_logistic.user'),
        ),
        migrations.CreateModel(
            name='RequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('old_status', models.CharField(choices=[('PENDING', 'En attente'), ('OFFERS_RECEIVED', 'Offres reçues'), ('ASSIGNED', 'Assignée'), ('IN_PROGRESS', 'En cours'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée')], max_length=20)),
                ('new_status', models.CharField(choices=[('PENDING', 'En attente'), ('OFFERS_RECEIVED', 'Offres reçues'), ('ASSIGNED', 'Assignée'), ('IN_PROGRESS', 'En cours'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('transport_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='africa_logistic.transportrequest')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='africa_logistic.user')),
            ],
            options={
                'verbose_name': 'Historique de statut',
                'verbose_name_plural': 'Historiques de statuts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to='africa_logistic.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to='legal_documents/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('type_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='africa_logistic.typedocumentlegal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_documents', to='africa_logistic.user')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_legal_documents', to='africa_logistic.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User2FA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('secret_key', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_fa', to='africa_logistic.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserConnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='africa_logistic.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to='africa_logistic.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
